### PR TITLE
Add handlebars templating

### PR DESCRIPTION
**Pull request by drjonnicholson**
Hey, starting to look at Bookmarklets for something and found your plugin. Thought I'd have a go at adding the template support mentioned. This PR:

- Adds Handlebars template engine
- Migrated HTML to hbs template as default
- Added ability to pass a path to a template file
- Added examples for custom HTML and custom React component output

Let me know what you think

### CODE REVIEW

**Comment by tomrule007** [comment]
@drjonnicholson thanks for taking the time to create this pr! Give me a few days to review it and hopefully we can get it merged in soon :)

**Comment by drjonnicholson** [comment]
No rush @tomrule007 - any changes let me know, happy to update

**Comment by drjonnicholson** [comment]
Hey @tomrule007, any thoughts / feedback?

**Comment by tomrule007** [comment]
@drjonnicholson thanks for the contribution!

I updated the Readme giving you credit for the template engine change and also published the new version.

https://www.npmjs.com/package/bookmarklet-webpack-plugin/v/1.1.0

**Pull request merged**
